name: senang_launcher
version: 0.0.3+3
publish_to: none
description: Senang Launcher
environment: 
  sdk: '>=3.3.0 <4.0.0'
dependencies: 
  access_wallpaper: 1.0.0
  auto_route: 8.1.3
  cupertino_icons: 1.0.6
  device_apps: 2.2.0
  flutter_animate: 4.5.0
  flutter_bloc: 8.1.5
  flutter_colorpicker: 1.0.3
  flutter_settings_ui: 3.0.1
  freezed_annotation: 2.4.1
  gap: 3.0.1
  intl: any
  json_annotation: 4.9.0
  notification_listener_service: 0.3.3
  package_info_plus: 8.0.0
  path: any
  path_provider: 2.1.3
  sembast: 3.7.1
  sembast_sqflite: 2.2.0
  sqflite: 2.3.3+1
  vibration: 1.8.4
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies: 
  auto_route_generator: any
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  pubspec_dependency_sorter: ^1.0.4
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  generate: true # Add this line
